// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyChamSocThuCung_UNETI3_TI17A5HN.Data;

#nullable disable

namespace QuanLyChamSocThuCung_UNETI3_TI17A5HN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChamSocThuCung_UNETI3_TI17A5HN.Models.ChiTietGoiDichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("MaGoi")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaGoi", "MaDichVu")
                        .IsUnique();

                    b.ToTable("ChiTietGoiDichVus");
                });

            modelBuilder.Entity("QuanLyChamSocThuCung_UNETI3_TI17A5HN.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NhomDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("QuanLyChamSocThuCung_UNETI3_TI17A5HN.Models.GoiDichVu", b =>
                {
                    b.Property<int>("MaGoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGoi"));

                    b.Property<decimal>("GiaGoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaKhuyenMai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaGoi");

                    b.ToTable("GoiDichVus");
                });

            modelBuilder.Entity("QuanLyChamSocThuCung_UNETI3_TI17A5HN.Models.ChiTietGoiDichVu", b =>
                {
                    b.HasOne("QuanLyChamSocThuCung_UNETI3_TI17A5HN.Models.DichVu", "DichVu")
                        .WithMany("ChiTietGoiDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyChamSocThuCung_UNETI3_TI17A5HN.Models.GoiDichVu", "GoiDichVu")
                        .WithMany("ChiTietGoiDichVus")
                        .HasForeignKey("MaGoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("GoiDichVu");
                });

            modelBuilder.Entity("QuanLyChamSocThuCung_UNETI3_TI17A5HN.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietGoiDichVus");
                });

            modelBuilder.Entity("QuanLyChamSocThuCung_UNETI3_TI17A5HN.Models.GoiDichVu", b =>
                {
                    b.Navigation("ChiTietGoiDichVus");
                });
#pragma warning restore 612, 618
        }
    }
}
